# -*- coding: utf-8 -*-
"""ML_supervised.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFvMVIsa-niQrfzJiOOi_rpMiP2SYhFL
"""

# linear regression method
import numpy as np
import pandas as pd

data ={
    "Experience": [1, 2, 3, 4, 5],
    "Salary": [30, 35, 40, 50, 55]
}
df=pd.DataFrame(data)
df
X=df["Experience"].values
y=df["Salary"].values
x_test =np.mean(X)
y_test=np.mean(y)
print("x_test and y_test    :",x_test,",",y_test)

numerator = np.sum((X-x_test)*(y-y_test))
denominator =np.sum((X-x_test)**2)
m = numerator / denominator
print("Slope of the graph   :",m)

b = y_test -(m * x_test)
print("starting point of the grapy :",b)
print("salary =",m,"* Experince + ",b)

new_experince = 7
predict = (m * new_experince)+b
print("given new data       :",new_experince)
print("pridiction the salary :",predict)

data = {
    "Experience": [1, 2, 3, 4, 5],
    "Salary": [30, 35, 40, 50, 55]
}
df = pd.DataFrame(data)
# print(df)

X =df["Experience"].values
y =df["Salary"].values
#print(X)
#print(y)

x_mean =np.mean(X)
y_mean =np.mean(y)
print("x_mean :",x_mean)
print("y_mean :",y_mean)

numerator = np.sum((X-x_mean)*(y-y_mean))
denominator = np.sum((X - x_mean)**2)
#slope finded
m = numerator / denominator
print("Slope :",m)
#intercept point finded
b = (y_mean -(m * x_mean))
print("Intercept value :",b)
print("salary =",m,"* Experince + ",b)

#now the new input give and get output
new_experince = 7
pridect =(m * new_experince + b)
print("Experince new data :",new_experince)
print("Exceptation Salary :",pridect)

#>>> Linear Regression Method

Data = {
    "Experience": [1, 2, 3, 4, 5],
    "Salary": [25000, 35000, 45000, 60000, 80000]
}
df = pd.DataFrame(Data)

x =df["Experience"].values
y =df["Salary"].values

x_mean =np.mean(x)
y_mean =np.mean(y)

numerator = np.sum((x-x_mean)*(y-y_mean))
denominator =np.sum((x-x_mean)**2)

m = numerator / denominator

b=y_mean - (m * x_mean)

#print("salary =",m,"* Experince +",b)

while True:
  interview =input(">>> Are you Attending the interview Now,says (Yes/No) :")
  if interview.lower() == "yes":
    new_experince = int(input(">>> How Many Years Of Experience Do You Have :"))
    if new_experince >= 0 and new_experince < 20:
      prediction =(m *new_experince)  + b
      print(f"\n{"-"*40}")
      print("Candidates Experience :",new_experince,"Years")
      print("We Can Offer You This Salary :",prediction)
      print(f"{"-"*40}\n")
    else:
      print(f"\n{">"*58}")
      print("We Want The Candidates Within 0 to 20 Years of experience!")
      print(f"{"<"*58}\n")
  elif interview.lower() == "no":
    print("\nThank You For Your Response")
    print("="*28)
    break
  else:
    print("\nPleas Enter Yes Or No !!! \n")

# >>> KNN classification regression

import numpy as np
import pandas as pd
data ={
    "distance_km":[5,6,7,8,9,10,11,12,13,14,15,16],
    "duration_min":[10,15,20,25,30,35,40,45,50,55,60,65],
    "catagory":["short","short","short","short","medium","medium","medium","medium","long","long","long","long"]
}
df=pd.DataFrame(data)
X =df[["distance_km","duration_min"]]
y =df["catagory"]

from sklearn.neighbors import KNeighborsClassifier
model =KNeighborsClassifier(n_neighbors=3,metric = "euclidean")
model.fit(X,y)
def rider():
  distance = float(input("Enter your distance in Km :"))
  duration =int(input("Enter your duration in Minutes :"))
  x_test =[[distance,duration]]
  prediction =model.predict(x_test)
  print("\n<<<Ride Prediction>>>")
  print("Distance :",distance,"Km")
  print("Duration :",duration,"Mins")
  print("Prediction catagory :",prediction[0],"\n")
while True:
  code_run =input("Enter Start or exist : ")
  if code_run.lower() == "start":
    print("Let's Start a new Ride...")
    rider()
  elif code_run.lower() == "exist":
    print("\n>>> Have a nice Journey <<<")
    break
  else:
    print("please enter Start or Exist")

